name: "Unit tests"
description: "Unit tests"
inputs:
  shell:
    required: true
    description: "Shell to use depending on runner os"

runs:
  using: "composite"
  steps:
    - name: Unit tests
      run: ./gradlew test --stacktrace
      shell: ${{ inputs.shell }}